version: '3.8'

services:
  api:
    build: .
    container_name: financial-tracker-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=financial_tracker
      - DEBUG=true
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    networks:
      - financial-tracker-network

  mongodb:
    image: mongo:5.0
    container_name: financial-tracker-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    driver: bridge

volumes:
  mongodb-data:
